name: Checkmarx Scan
on:
  push:
    branches: 
       checkmarx-scan
jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
      with:
        project: HylandRPA.Api.Heart # <-- Insert Checkmarx SAST Project Name
        team: CxServer\AppSec\Hyland\DevSec\Misc\RPA
        checkmarx_url: https://srv-cxsuite.onbase.net/cxwebclient/
        #checkmarx_signinmethod: onbase
        checkmarx_username: ${{ secrets.CXEMAIL }}
        checkmarx_password: ${{ secrets.CXPASSWORD }}
        github_token: ${{ secrets.GITHUBTOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: log.log
        path: log.log
